import "../styles/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  const navData = [
    { name: "Home", link: "/" },
    { name: "Products", link: "/products" },
    { name: "Categories", link: "/categories" },
    { name: "Manufacturers", link: "/manufacturers" },
  ];
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <nav className="bg-white border-gray-200 dark:bg-gray-900">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="/" className="flex items-center">
              <img
                src="https://i.ibb.co/hLNL7Pr/image-removebg-preview.png"
                className="h-8 mr-3"
                alt=""
              />
              <span className="self-center text-3xl font-semibold whitespace-nowrap dark:text-white">
                emart
              </span>
            </a>
            <div
              className="hidden w-full md:block md:w-auto"
              id="navbar-default"
            >
              <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                {navData.map((nav, index) => (
                  <li key={index}>
                    <a
                      href={nav.link}
                      className="block py-2 pl-3 pr-4 text-black"
                      aria-current="page"
                    >
                      {nav.name}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </nav>
        <hr />
        {children}
        <footer className="bg-slate-900 rounded-lg shadow m-4">
          <div className="w-full mx-auto max-w-screen-xl p-2">
            <span className="text-md text-white bg-slate-900">
              © Realia | TWO THOUSAND TWENTY THREE | Team Gazette
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
